def month(n):
    If n==1:
        return ("enero”)
    elif n==2:
        return ("febrero”)
    elif n==3:
        return ("marzo”)
    elif n==4:
        return ("abril”)
    elif n==5:
        return ("mayo”)
    elif n==6:
        return ("junio”)
    elif n==7:
        return ("julio”)
    elif n==8:
        return ("agosto")
    elif n==9:
    return ("septiembre")
    elif n==10:
return ("octubre")
elif n==11:
return ("noviembre")
elif n==12:
return ("diciembre")
else:
return (“error”)
